Relade/Store/OtomationStore/OtomationStore/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using OtomationStore.Areas.HelpPage.ModelDescriptions;
using OtomationStore.Areas.HelpPage.Models;

namespace OtomationStore.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Relade/Store/OtomationStore/OtomationStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Relade/Store/OtomationStore/OtomationStore/Views/Shared/_Layout_Producer.cshtml
@using OtomationStore.Models

<!DOCTYPE html>
<html ng-app>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/Product/ListAllProducts">
                    <font size="4" class="navbar-brand">
                        OTOMATION STORE
                    </font>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/Product/ListAllProducts">List All Products</a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" action="/Product/Details">
                    <div class="form-group">
                        <input type="text" name="id" class="form-control" placeholder="Product Code">
                    </div>
                    <button type="submit" class="btn btn-default">Get Details</button>
                </form>
                
                
                    <div class="nav navbar-nav navbar-right" style="padding-top: 8px;">
                        <div class="btn-group">
                            @if (Session["producer_name"] != null)
                            {
                            <button type="button" class="btn btn-default">@Session["name"].ToString()</button>
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="/Producer/Index">This Company</a></li>
                                    <li><a href="/Producer/ListProducts">My Products</a></li>
                                    <li><a href="/Product/AddProduct">Add Product</a></li>
                                    <li><a href="/Producer/Logout">Logout</a></li>
                                </ul>
                            }
                            else
                            {
                                <li><a href="/Producer/Login"><span class="glyphicon glyphicon-log-in" style="padding-top: 8px;"></span> Login</a></li>
                            }
                        </div>
                    </div>
               
            </div>
        </div>
    </div>
    <div class="container body-content">

        @if (TempData["message"] != null)
        {
            MessageModel message_model = (MessageModel)TempData["message"];
            TempData["message"] = null;
            <br />
            <div class="alert  alert-dismissable @message_model.MessageTypeToString()">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong> @message_model.caption </strong> @message_model.message
            </div>
        }

        @RenderBody()

        <footer></footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js"></script>
</body>
</html>